#!/bin/bash

curl https://www.publicdomainpictures.net/pictures/50000/velka/sunset-5-1369039079YoH.jpg > sunset.jpg

aws s3 cp sunset.jpg s3://ds2002-mqq9sb/

aws s3 presign --expires-in 604800 s3://ds2002-mqq9sb/sunset.jpg

# link: https://ds2002-mqq9sb.s3.us-east-1.amazonaws.com/sunset.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAZI2LHW67MFC52MHB%2F20240310%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240310T213727Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Security-Token=FwoGZXIvYXdzECcaDDgjfFsaV9bt%2BZ4N3iLEAUi5YljdUqfKMhKRNlDoLV78ONgv86a6P%2BIr55rpIZhSTg4hCBPPQlu2NrqTiV7Aw8wnDknIm36Msgetn3jbnJcu9JDKyBemXGDCKIOFONPp%2FE4nIbrHI2C90Gq4Vo2riD7JwLmGdjup40zQS%2B%2BFLV6I%2FIlPoAxunwYFvnSYCcIQrM8iMSuMC30UVDGowXrsqktOaHcqE7oP2X20XMKgkSzfezRIdSmpBsYMFe23bu7Fi8e473l%2FV0tT4I9rY2d8o1ei4LIokM24rwYyLbyl5s%2Fz%2F72GH3cA3TseWTlzTR58Le0dOwj%2FzV7yJVTseP2nBd78YoC6aw8qHg%3D%3D&X-Amz-Signature=8ba2ff1004a6741c4e9772022c0d14b92188a91be5b8ce0f6429a000d05d4a77
