#!/opt/anaconda3/bin/python3

import urllib.request
import boto3

url = 'https://th.bing.com/th/id/R.fc2396311f5b8e5b04295bd0da953505?rik=uZlQQSdemAYY7Q&riu=http%3a%2f%2fupload.wikimedia.org%2fwikipedia%2fcommons%2f7%2f79%2fFireworks_-_Adelaide_Skyshow_2010.jpg&ehk=CpxS7VxFJ1Sr1pJjYayz6071oIlujCk4v2T8SlZnAXY%3d&risl=&pid=ImgRaw&r=0'
file_name = "fireworks.jpg"

urllib.request.urlretrieve(url, file_name)

s3 = boto3.client('s3', region_name="us-east-1")

bucket = 'ds2002-mqq9sb'
local_file = "fireworks.jpg"

with open(file_name, 'rb') as file:
    resp = s3.put_object(Body=file, 
                         Bucket=bucket,
                         Key=file_name,
                         ContentType='image/jpg')

expires_in = 604800

response = s3.generate_presigned_url(
    'get_object',
    Params={'Bucket': bucket, 'Key': local_file},
    ExpiresIn=expires_in
    )

print(response)

# link: https://ds2002-mqq9sb.s3.amazonaws.com/fireworks.jpg?AWSAccessKeyId=ASIAZI2LHW67MFC52MHB&Signature=ntBsoWZVzssIvRqoK6mJw2AHeHY%3D&x-amz-security-token=FwoGZXIvYXdzECcaDDgjfFsaV9bt%2BZ4N3iLEAUi5YljdUqfKMhKRNlDoLV78ONgv86a6P%2BIr55rpIZhSTg4hCBPPQlu2NrqTiV7Aw8wnDknIm36Msgetn3jbnJcu9JDKyBemXGDCKIOFONPp%2FE4nIbrHI2C90Gq4Vo2riD7JwLmGdjup40zQS%2B%2BFLV6I%2FIlPoAxunwYFvnSYCcIQrM8iMSuMC30UVDGowXrsqktOaHcqE7oP2X20XMKgkSzfezRIdSmpBsYMFe23bu7Fi8e473l%2FV0tT4I9rY2d8o1ei4LIokM24rwYyLbyl5s%2Fz%2F72GH3cA3TseWTlzTR58Le0dOwj%2FzV7yJVTseP2nBd78YoC6aw8qHg%3D%3D&Expires=1710711492
