#!/opt/anaconda3/bin/python/

import boto3

s3 = boto3.client('s3', region_name="us-east-1")

bucket = 'ds2002-mqq9sb'
local_file = 'flower.jpg'

resp = s3.put_object(
    ACL = 'public-read',
    Body = local_file,
    Bucket = bucket,
    Key = local_file
)
